academy/Academy/Academy/Controllers/AcademyController.cs
using Academy.Data;
using Academy.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;

namespace Academy.Controllers
{
    public class AcademyController : Controller
    {
        private readonly AcademyContext _academy;
        public AcademyController(AcademyContext academy)
        {
            _academy = academy;
        }

        public ActionResult Index()
        {
            return View(_academy.Alunos.Include(x => x.Treinos).Include(x => x.Personal));
        }

        public IActionResult Details(int id)
        {
            var aluno = _academy.Alunos.Include(x => x.Personal).FirstOrDefault(x => x.AlunoId == id);

            return View(aluno);
        }

        public IActionResult Create()
        {
            ViewBag.Personais = new SelectList(_academy.Personais.OrderBy(x => x.Nome) , "PersonalId", "Nome");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Aluno aluno)
        {
            _academy.Alunos.Add(aluno);
            _academy.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var aluno = _academy.Alunos.Find(id);
            ViewBag.Personais = new SelectList(_academy.Personais.OrderBy(x => x.Nome), "PersonalId", "Nome");
            return View(aluno);
        }

        [HttpPost]
        public IActionResult Edit(Aluno aluno)
        {
            _academy.Alunos.Update(aluno);
            _academy.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var aluno = _academy.Alunos.Find(id);
            return View(aluno);
        }

        [HttpPost]
        public IActionResult Delete(Aluno aluno)
        {
            _academy.Alunos.Remove(aluno);
            _academy.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult CreateTreinos()
        {
            ViewBag.Alunos = new SelectList(_academy.Alunos.OrderBy(x => x.Nome), "AlunoId", "Nome");
            ViewBag.Exercicios = new MultiSelectList(_academy.Exercicios.OrderBy(x => x.Nome), "ExercicioId", "Nome");
            return View();
        }

        [HttpPost]
        public IActionResult CreateTreinos(Treino treino, int[] ExerciciosSelecionados)
        {
            treino.Data = DateTime.Now;
            treino.Exercicios = new List<Exercicio>();
            if (ExerciciosSelecionados != null)
            {
                foreach (var exercicioId in ExerciciosSelecionados)
                {
                    var exercicio = _academy.Exercicios.Find(exercicioId);
                    if (exercicio != null)
                    {
                        treino.Exercicios.Add(exercicio);
                    }
                }
            }

            _academy.Treinos.Add(treino);
            _academy.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult DeleteTreinos(int id)
        {
            var treino = _academy.Treinos.Include(x => x.Aluno).FirstOrDefault(x => x.TreinoId == id);

            var alunoId = treino.AlunoId;

            _academy.Treinos.Remove(treino);
            _academy.SaveChanges();
            return RedirectToAction("DetailsTreino", new { id = alunoId });
        }

        public IActionResult DetailsTreino(int id)
        {
            var treino = _academy.Treinos.Where(x => x.AlunoId == id).Include(x => x.Aluno).Include(x => x.Exercicios).ToList();  
            ViewBag.Aluno = _academy.Alunos.Find(id).Nome;
            return View(treino);
        }

        public IActionResult EditTreino(int id)
        {
            var treino = _academy.Treinos.Include(x => x.Aluno).Include(x => x.Exercicios).FirstOrDefault(x => x.TreinoId == id);
            ViewBag.Exercicios = new MultiSelectList(_academy.Exercicios.OrderBy(x => x.Nome), "ExercicioId", "Nome");

            return View(treino);
        }

        [HttpPost]
        public IActionResult EditTreino(int treinoId, int[] ExerciciosSelecionados)
        {
            var treino = _academy.Treinos.Include(x => x.Aluno).Include(x => x.Exercicios).FirstOrDefault(x => x.TreinoId == treinoId);
            treino.Exercicios = null;
            _academy.SaveChanges();
            treino.Exercicios = new List<Exercicio>();
            if (ExerciciosSelecionados != null)
                foreach(var exercicioId in ExerciciosSelecionados)
                {
                    var exercicio = _academy.Exercicios.Find(exercicioId);
                    if (exercicio != null)
                        treino.Exercicios.Add(exercicio);
                }

            treino.Data = DateTime.Now;
            _academy.SaveChanges();

            return RedirectToAction("DetailsTreino", new { id = treino.AlunoId });
        }
    }
}

academy/Academy/Academy/Controllers/ExercicioController.cs
using Academy.Data;
using Academy.Models;
using Microsoft.AspNetCore.Mvc;

namespace Academy.Controllers
{
    public class ExercicioController : Controller
    {
        private readonly AcademyContext _academy;

        public ExercicioController(AcademyContext academy)
        {
            _academy = academy;
        }

        public IActionResult Index()
        {
            return View(_academy.Exercicios);
        }

        public IActionResult Details(int id)
        {
            var exercicio = _academy.Exercicios.Find(id);
            return View(exercicio);
        }

        public IActionResult Create() =>
            View();

        [HttpPost]
        public IActionResult Create(Exercicio exercicio)
        {
            _academy.Exercicios.Add(exercicio);
            _academy.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var exercicio = _academy.Exercicios.Find(id);
            _academy.Exercicios.Remove(exercicio);
            _academy.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var exercicio = _academy.Exercicios.Find(id);
            return View(exercicio);
        }

        [HttpPost]
        public IActionResult Edit(Exercicio exercicio)
        {
            _academy.Exercicios.Update(exercicio);
            _academy.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

academy/Academy/Academy/Controllers/PersonalController.cs
using Academy.Data;
using Academy.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Academy.Controllers
{
    public class PersonalController : Controller
    {
        private readonly AcademyContext _academy;

        public PersonalController(AcademyContext academy)
        {
            _academy = academy;
        }

        public IActionResult Index()
        {
            return View(_academy.Personais);
        }

        public IActionResult Create() =>
            View();

        [HttpPost]
        public IActionResult Create(Personal personal)
        {
            _academy.Personais.Add(personal);
            _academy.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            var personal = _academy.Personais.Include(x => x.Alunos).FirstOrDefault(x => x.PersonalId == id);
            return View(personal);
        }

        public IActionResult Delete(int id)
        {
            var personal = _academy.Personais.Find(id);
            _academy.Personais.Remove(personal);
            _academy.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var personal = _academy.Personais.Find(id);
            return View(personal);
        }

        [HttpPost]
        public IActionResult Edit(Personal personal)
        {
            _academy.Personais.Update(personal);
            _academy.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

academy/Academy/Academy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Academy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Academy.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Academy" asp-action="Index">Academy</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Academy" asp-action="Index">Academy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personal" asp-action="Index">Personal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exercicio" asp-action="Index">Exercicios</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>